version: "3"
services:
  2022-10-23-nhentai-to-pdf-server:
    container_name: 2022-10-23-nHentai-to-PDF-Server
    image: 9-fs/2022-10-23-nhentai-to-pdf-server
    environment:
      - HOST_OS=Unraid
      - TZ=UTC
    volumes:
      - /mnt/user/appdata/2022-10-23-nhentai-to-pdf-server/config/:/app/config/:rw
      - /mnt/user/appdata/2022-10-23-nhentai-to-pdf-server/log/:/app/log/:rw
      - /mnt/user/media/hentai/:/app/hentai/:rw
    network_mode: bridge
    deploy:
      resources:
        limits:
          memory: 20G
    user: 99:100
networks: {}
